import { JSX } from "react";
import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import { AppInitializer } from "@/common/AppInitializer";
import Header from "@/common/organisms/Header";
import Sidebar from "@/common/organisms/Sidebar";
import "./globals.css";

/*
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"]
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"]
});
 */

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>): JSX.Element {
  return (
    <html lang="ja">
      <body>
        {/* className={`${geistSans.variable} ${geistMono.variable}`} */}
        {/* Header */}
        <header>
          <Header />
        </header>

        {/* Content */}
        <main>
          {/* 削除 className={styles.main} */}
          {/* サイドバー */}
          <Sidebar />

          {/* メインコンテンツ、content内はSSGのためコンポーネント化しない */}
          <div className="content">
            {children}
            {/* importが重いもののプリロード */}
            <AppInitializer />
          </div>
        </main>

        {/* Footer */}
        <footer>{/* 削除 className={styles.footer} */}</footer>
      </body>
    </html>
  );
}
