import type { Metadata } from "next";
import Image from "next/image";
import styles from "./page.module.css";
import { Inter } from "next/font/google";
import "./globals.css";

// Bootstrap
import "bootstrap/dist/css/bootstrap.min.css";

// Root layout
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div
          style={{
            // flexbox利用
            display: "flex",
            // 主軸が走る方向
            flexDirection: "column",
            background: "white",
            height: "100vh",
          }}
        >
          <div>
            <div style={{ margin: "5px" }}>
              <header>Next.js app dashboard</header>
            </div>
          </div>
          <div>
            <div style={{ margin: "5px" }}>
              <nav>Menu</nav>
            </div>
          </div>
          <div style={{ borderTop: "1px solid gray", flex: 1, overflowY: "auto", overflowX: "hidden" }}>
            <div style={{ margin: "5px" }}>
              <main>{children}</main>
            </div>
          </div>
          <div style={{ borderTop: "1px solid gray" }}>
            <div style={{ margin: "5px" }}>
              <footer>
                <Image className={styles.logo} src="/next.svg" alt="Next.js Logo" width={45} height={10} priority style={{ marginLeft: "5px" }} />
              </footer>
            </div>
          </div>
        </div>
      </body>
    </html>
  );
};

export default RootLayout;
